### ISSUE TITLE
Cannot include package with binary target

### ISSUE THREAD

**Issue by pswaminathan** [cgrindel/swift_bazel#153]
Probably mirrors cgrindel/rules_spm#175, but figured I would leave it here for completeness. Example is Firebase:

```
.package(url: "https://github.com/firebase/firebase-ios-sdk", .exact("8.9.1")),
```

```
ERROR: An error occurred during the fetch of repository 'swiftpkg_firebase_ios_sdk':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_p/5462d161dadab65df3f9fb5a8ecf08b9/external/cgrindel_swift_bazel/swiftpkg/internal/swift_package.bzl", line 50, column 28, in _swift_package_impl
		pkg_info = pkginfos.get(repository_ctx, directory, env = env)
	File "/private/var/tmp/_bazel_p/5462d161dadab65df3f9fb5a8ecf08b9/external/cgrindel_swift_bazel/swiftpkg/internal/pkginfos.bzl", line 71, column 33, in _get
		return _new_from_parsed_json(
	File "/private/var/tmp/_bazel_p/5462d161dadab65df3f9fb5a8ecf08b9/external/cgrindel_swift_bazel/swiftpkg/internal/pkginfos.bzl", line 273, column 35, in _new_from_parsed_json
		_new_target_from_json_maps(
	File "/private/var/tmp/_bazel_p/5462d161dadab65df3f9fb5a8ecf08b9/external/cgrindel_swift_bazel/swiftpkg/internal/pkginfos.bzl", line 159, column 23, in _new_target_from_json_maps
		return _new_target(
	File "/private/var/tmp/_bazel_p/5462d161dadab65df3f9fb5a8ecf08b9/external/cgrindel_swift_bazel/swiftpkg/internal/pkginfos.bzl", line 564, column 24, in _new_target
		validations.in_list(
	File "/private/var/tmp/_bazel_p/5462d161dadab65df3f9fb5a8ecf08b9/external/cgrindel_swift_bazel/swiftpkg/internal/validations.bzl", line 10, column 13, in _in_list
		fail(err_msg, value)
Error in fail: Unrecognized target type. type: binary
ERROR: /Users/p/Code/ergatta/arm2/WORKSPACE:113:19: fetching swift_package rule //external:swiftpkg_firebase_ios_sdk: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_p/5462d161dadab65df3f9fb5a8ecf08b9/external/cgrindel_swift_bazel/swiftpkg/internal/swift_package.bzl", line 50, column 28, in _swift_package_impl
		pkg_info = pkginfos.get(repository_ctx, directory, env = env)
	File "/private/var/tmp/_bazel_p/5462d161dadab65df3f9fb5a8ecf08b9/external/cgrindel_swift_bazel/swiftpkg/internal/pkginfos.bzl", line 71, column 33, in _get
		return _new_from_parsed_json(
	File "/private/var/tmp/_bazel_p/5462d161dadab65df3f9fb5a8ecf08b9/external/cgrindel_swift_bazel/swiftpkg/internal/pkginfos.bzl", line 273, column 35, in _new_from_parsed_json
		_new_target_from_json_maps(
	File "/private/var/tmp/_bazel_p/5462d161dadab65df3f9fb5a8ecf08b9/external/cgrindel_swift_bazel/swiftpkg/internal/pkginfos.bzl", line 159, column 23, in _new_target_from_json_maps
		return _new_target(
	File "/private/var/tmp/_bazel_p/5462d161dadab65df3f9fb5a8ecf08b9/external/cgrindel_swift_bazel/swiftpkg/internal/pkginfos.bzl", line 564, column 24, in _new_target
		validations.in_list(
	File "/private/var/tmp/_bazel_p/5462d161dadab65df3f9fb5a8ecf08b9/external/cgrindel_swift_bazel/swiftpkg/internal/validations.bzl", line 10, column 13, in _in_list
		fail(err_msg, value)
Error in fail: Unrecognized target type. type: binary
ERROR: no such package '@swiftpkg_firebase_ios_sdk//': Unrecognized target type. type: binary
Loading: 0 packages loaded
```

**Comment by pswaminathan** [comment]
Just a note that I tested [f3ee05d](https://github.com/cgrindel/swift_bazel/commit/f3ee05dee78bd4707abc5cf2b460d7bbf65f58b2) and saw:

* Firebase: unable to import for some platform errors (I think you may already be aware of this)
* Braze (what I opened the issue in rules_spm with): worked!

**Comment by pswaminathan** [comment]
Great! I can also test with other versions as well as it gets closer—just wanted to start off with the same version we're using.

**Comment by cgrindel** [comment]
@pswaminathan Which features from firebase do you use? I am adding examples from [this quickstart repo](https://github.com/firebase/quickstart-ios) to ensure that `swift_bazel` handles things properly.

Also, I may end up breaking up verifying the different parts of firebase into separate tickets. That will allow me to declare victory on this ticket, as I added binary target support.

**Comment by AttilaTheFun** [comment]
@cgrindel @pswaminathan I'm also encountering this issue with Firebase and Agora.
From Firebase I'm using the FirebaseAnalyticsWithoutAdId target and from Agora:
https://github.com/AgoraIO/AgoraRtcEngine_iOS/blob/main/Package.swift
I'm using their AgoraRtcKit target.

**Comment by cgrindel** [comment]
@AttilaTheFun Support for binary targets is available in the `main` branch. I have not created a release since adding it. I was going to put a couple more changes in before releasing. Can you try using the latest from the `main` branch?

**Comment by AttilaTheFun** [comment]
Hi @cgrindel! I'm not sure how to use a branch with a http archive in bazel. What would I replace this with to use the main branch?

```
http_archive(
    name = "cgrindel_swift_bazel",
    sha256 = "fd77181e45fbb9ab6ddedf59f3f2d4cf0c173919a6de8d4a398d99fd965d5ce5",
    strip_prefix = "swift_bazel-0.2.0",
    urls = [
        "http://github.com/cgrindel/swift_bazel/archive/v0.2.0.tar.gz",
    ],
)

load("@cgrindel_swift_bazel//:deps.bzl", "swift_bazel_dependencies")
```

Alternately maybe you could create a 0.3.0 pre-release?

**Comment by pswaminathan** [comment]
> Which features from firebase do you use?

@cgrindel from our manually generated build files, here is what we are depending on:

```
            "@Firebase//:FirebaseAnalytics",
            "@Firebase//:FirebaseCore",
            "@Firebase//:FirebaseCrashlytics",
            "@Firebase//:FirebaseMessaging",
            "@Firebase//:FirebaseRemoteConfig",
```

This corresponds roughly to the XCFrameworks exported, and which we would probably be importing. I can test out master some time this week and see if that works for us.

> Also, I may end up breaking up verifying the different parts of firebase into separate tickets. That will allow me to declare victory on this ticket, as I added binary target support.

That works for me!

**Comment by cgrindel** [comment]
> @cgrindel from our manually generated build files, here is what we are depending on:
> 
> ```
>             "@Firebase//:FirebaseAnalytics",
>             "@Firebase//:FirebaseCore",
>             "@Firebase//:FirebaseCrashlytics",
>             "@Firebase//:FirebaseMessaging",
>             "@Firebase//:FirebaseRemoteConfig",
> ```
The only modules in your list that are not covered by an example are `@Firebase//:FirebaseCrashlytics` and `@Firebase//:FirebaseMessaging`. I added #223 and #224 to track.

**Comment by cgrindel** [comment]
Declaring victory on this issue as binary target support has been added.

@AttilaTheFun Let me know here or in a new bug, if you have issues using [release 0.2.1](https://github.com/cgrindel/swift_bazel/releases/tag/v0.2.1) or later.

**Comment by AttilaTheFun** [comment]
@cgrindel I tried to use the 0.2.1 release but I got this error:
```
INFO: Running command line: bazel-bin/Tidy :UpdateSwiftPackages :UpdateBuildFiles
ERROR: /Users/logan/Developer/Swift/Apps/Snag/BUILD:52:15: no such package '@bazel_skylib//gazelle/bzl': BUILD file not found in directory 'gazelle/bzl' of external repository @bazel_skylib. Add a BUILD file to a directory to mark it as a package. and referenced by '//:GazelleBinary'
ERROR: Analysis of target '//:UpdateSwiftPackages' failed; build aborted: 
```

These are the only changes I have in my repo to update to 0.2.1:
```
     dependencies: [
         .package(url: "https://github.com/AgoraIO/AgoraRtcEngine_iOS", .upToNextMajor(from: "3.4.8")),
         .package(url: "https://github.com/apollographql/apollo-ios", .upToNextMinor(from: "0.48.0")),
-        // .package(url: "https://github.com/firebase/firebase-ios-sdk", .upToNextMajor(from: "10.0.0")),
+        .package(url: "https://github.com/firebase/firebase-ios-sdk", .upToNextMajor(from: "10.0.0")),
         .package(url: "https://github.com/onevcat/Kingfisher", .upToNextMajor(from: "7.5.0")),
         // .package(url: "https://github.com/marmelroy/PhoneNumberKit", .upToNextMajor(from: "3.3.3")),
         .package(url: "https://github.com/ReactiveX/RxSwift", .upToNextMajor(from: "6.0.0")),
diff --git a/WORKSPACE b/WORKSPACE
index 18d9f01ac..d00d7ebbe 100644
--- a/WORKSPACE
+++ b/WORKSPACE
@@ -6,10 +6,9 @@ load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
 
 http_archive(
     name = "cgrindel_swift_bazel",
-    sha256 = "fd77181e45fbb9ab6ddedf59f3f2d4cf0c173919a6de8d4a398d99fd965d5ce5",
-    strip_prefix = "swift_bazel-0.2.0",
+    sha256 = "2bcbe2947649f6433bf97258401c387eb41153c8adc378f84295628d879092d2",
     urls = [
-        "http://github.com/cgrindel/swift_bazel/archive/v0.2.0.tar.gz",
+        "https://github.com/cgrindel/swift_bazel/releases/download/v0.2.1/swift_bazel.v0.2.1.tar.gz",
     ],
 )
```

**Comment by cgrindel** [comment]
@AttilaTheFun I think that you might be running into the fact that [Skylib changed how they package their Gazelle extension](https://github.com/bazelbuild/bazel-skylib#gazelle-plugin). Note the new target for the Skylib language:
```python
gazelle_binary(
    name = "gazelle_bin",
    languages = DEFAULT_LANGUAGES + [
        "@bazel_skylib_gazelle_plugin//bzl",
    ],
)
```

#226 will update the `swift_bazel` README.md with the new Skylib target.

**Comment by AttilaTheFun** [comment]
@cgrindel I also tried adding Agora and it built but when I run the application in the iOS simulator it's crashing with this message:
```
Warning: Error creating LLDB target at path '/Users/logan/Library/Developer/Xcode/DerivedData/Phono-birejekbhxukppblfutmohyojdym/Build/Products/bazel-out/ios-x86_64-min14.0-applebin_ios-ios_x86_64-dbg-ST-3d49fca66c8d/bin/Phono/Phono/Phono.app'- using an empty LLDB target which can cause slow memory reads from remote devices: the specified architecture 'arm64-*-*' is not compatible with 'x86_64-apple-ios14.0.0-simulator' in '/Users/logan/Library/Developer/Xcode/DerivedData/Phono-birejekbhxukppblfutmohyojdym/Build/Products/bazel-out/ios-x86_64-min14.0-applebin_ios-ios_x86_64-dbg-ST-3d49fca66c8d/bin/Phono/Phono/Phono.app/Phono'
dyld[78318]: Library not loaded: @rpath/AgoraCore.framework/AgoraCore
  Referenced from: <CFDCA36E-5D08-3378-964B-7FA9AF503399> /Users/logan/Library/Developer/CoreSimulator/Devices/05D87724-92DF-41DD-9AA6-0E25DE53CF5E/data/Containers/Bundle/Application/93F98452-6026-491C-9C48-B13BA31AB45B/Phono.app/Frameworks/AgoraRtcKit.framework/AgoraRtcKit
Message from debugger: Terminated due to signal 6
  Reason: tried: '/Users/logan/Library/Developer/Xcode/DerivedData/Phono-birejekbhxukppblfutmohyojdym/Build/Products/bazel-out/ios-x86_64-min14.0-applebin_ios-ios_x86_64-dbg-ST-3d49fca66c8d/bin/Phono/Phono/AgoraCore.framework/AgoraCore' (errno=2), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/AgoraCore.framework/AgoraCore' (errno=2), '/usr/lib/swift/AgoraCore.framework/AgoraCore' (errno=2, no dyld cache), '/Users/logan/Library/Developer/CoreSimulator/Devices/05D87724-92DF-41DD-9AA6-0E25DE53CF5E/data/Containers/Bundle/Application/93F98452-6026-491C-9C48-B13BA31AB45B/Phono.app/Frameworks/AgoraCore.framework/AgoraCore' (errno=2), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/AgoraCore.framework/AgoraCore' (errno=2), '/usr/lib/swift/AgoraCore.framework/AgoraCore' (errno=2, no dyld cache), '/Users/logan/Library/Developer/CoreSimulator/Devices/05D87724-92DF-41DD-9AA6-0E25DE53CF5E/data/Containers/Bundle/Application/93F98452-6026-491C-9C48-B13BA31AB45B/Phono.app/Frameworks/AgoraCore.framework/AgoraCore' (errno=2), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/AgoraCore.framework/AgoraCore' (errno=2)
```

My Package.swift has:
```
.package(url: "https://github.com/AgoraIO/AgoraRtcEngine_iOS", .upToNextMajor(from: "3.4.8")),
```

And my BUILD file has:
```
"@swiftpkg_agorartcengine_ios//:remote_archive_AgoraRtcKit.xcframework.zip_AgoraRtcKit",
```
