### ISSUE TITLE
TCA fails to be built (Unrecognized target type. type: system)

### ISSUE THREAD

**Issue by jpsim** [cgrindel/swift_bazel#235]
The Swift Composable Architecture (TCA) is a popular library for building iOS apps: https://github.com/pointfreeco/swift-composable-architecture

However, when I try to add it using swift_bazel, I get the following errors:

```
$ bazel build //Sources/MyExecutable:MyExecutable
INFO: Repository swiftpkg_swift_composable_architecture instantiated at:
  /Users/jsimard/src/swift_bazel/examples/pkg_manifest_minimal/WORKSPACE:62:19: in <toplevel>
  /Users/jsimard/src/swift_bazel/examples/pkg_manifest_minimal/swift_deps.bzl:51:18: in swift_dependencies
Repository rule swift_package defined at:
  /private/var/tmp/_bazel_jsimard/64a082b02cd2d1129dde7e92fdcc0ae0/external/cgrindel_swift_bazel/swiftpkg/internal/swift_package.bzl:167:32: in <toplevel>
ERROR: An error occurred during the fetch of repository 'swiftpkg_swift_composable_architecture':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_jsimard/64a082b02cd2d1129dde7e92fdcc0ae0/external/cgrindel_swift_bazel/swiftpkg/internal/swift_package.bzl", line 59, column 28, in _swift_package_impl
		pkg_info = pkginfos.get(repository_ctx, directory, env = env)
	File "/private/var/tmp/_bazel_jsimard/64a082b02cd2d1129dde7e92fdcc0ae0/external/cgrindel_swift_bazel/swiftpkg/internal/pkginfos.bzl", line 81, column 33, in _get
		return _new_from_parsed_json(
	File "/private/var/tmp/_bazel_jsimard/64a082b02cd2d1129dde7e92fdcc0ae0/external/cgrindel_swift_bazel/swiftpkg/internal/pkginfos.bzl", line 355, column 35, in _new_from_parsed_json
		_new_target_from_json_maps(
	File "/private/var/tmp/_bazel_jsimard/64a082b02cd2d1129dde7e92fdcc0ae0/external/cgrindel_swift_bazel/swiftpkg/internal/pkginfos.bzl", line 208, column 23, in _new_target_from_json_maps
		return _new_target(
	File "/private/var/tmp/_bazel_jsimard/64a082b02cd2d1129dde7e92fdcc0ae0/external/cgrindel_swift_bazel/swiftpkg/internal/pkginfos.bzl", line 693, column 24, in _new_target
		validations.in_list(
	File "/private/var/tmp/_bazel_jsimard/64a082b02cd2d1129dde7e92fdcc0ae0/external/cgrindel_swift_bazel/swiftpkg/internal/validations.bzl", line 10, column 13, in _in_list
		fail(err_msg, value)
Error in fail: Unrecognized target type. type: system
ERROR: /Users/jsimard/src/swift_bazel/examples/pkg_manifest_minimal/WORKSPACE:62:19: fetching swift_package rule //external:swiftpkg_swift_composable_architecture: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_jsimard/64a082b02cd2d1129dde7e92fdcc0ae0/external/cgrindel_swift_bazel/swiftpkg/internal/swift_package.bzl", line 59, column 28, in _swift_package_impl
		pkg_info = pkginfos.get(repository_ctx, directory, env = env)
	File "/private/var/tmp/_bazel_jsimard/64a082b02cd2d1129dde7e92fdcc0ae0/external/cgrindel_swift_bazel/swiftpkg/internal/pkginfos.bzl", line 81, column 33, in _get
		return _new_from_parsed_json(
	File "/private/var/tmp/_bazel_jsimard/64a082b02cd2d1129dde7e92fdcc0ae0/external/cgrindel_swift_bazel/swiftpkg/internal/pkginfos.bzl", line 355, column 35, in _new_from_parsed_json
		_new_target_from_json_maps(
	File "/private/var/tmp/_bazel_jsimard/64a082b02cd2d1129dde7e92fdcc0ae0/external/cgrindel_swift_bazel/swiftpkg/internal/pkginfos.bzl", line 208, column 23, in _new_target_from_json_maps
		return _new_target(
	File "/private/var/tmp/_bazel_jsimard/64a082b02cd2d1129dde7e92fdcc0ae0/external/cgrindel_swift_bazel/swiftpkg/internal/pkginfos.bzl", line 693, column 24, in _new_target
		validations.in_list(
	File "/private/var/tmp/_bazel_jsimard/64a082b02cd2d1129dde7e92fdcc0ae0/external/cgrindel_swift_bazel/swiftpkg/internal/validations.bzl", line 10, column 13, in _in_list
		fail(err_msg, value)
Error in fail: Unrecognized target type. type: system
ERROR: /Users/jsimard/src/swift_bazel/examples/pkg_manifest_minimal/Sources/MyExecutable/BUILD.bazel:3:13: //Sources/MyExecutable:MyExecutable depends on @swiftpkg_swift_composable_architecture//:Sources_ComposableArchitecture in repository @swiftpkg_swift_composable_architecture which failed to fetch. no such package '@swiftpkg_swift_composable_architecture//': Unrecognized target type. type: system
ERROR: Analysis of target '//Sources/MyExecutable:MyExecutable' failed; build aborted: Analysis failed
INFO: Elapsed time: 2.921s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (5 packages loaded, 0 targets configured)
```

Here's how I attempted to add it to one of this project's existing examples: https://github.com/cgrindel/swift_bazel/compare/main...jpsim:swift_bazel:jp-tca-errors

**Comment by cgrindel** [comment]
I have targeted this for 0.4.0. I am trying to button up 0.3.0, right now.

**Comment by cgrindel** [comment]
There are two issues with ensuring `swift_bazel` supports TCA:
1. There was an incorrect value in the valid target type list.
2. Test targets and targets associated with phantom products were not properly filtered out.

The `system` target that caused the failure that is mentioned in this issue is only used by the benchmark executable which is not a declared product. As a rule, `swift_bazel` does not attempt to build phantom products or targets that are only associated with phantom products, because SPM does not resolve external dependencies for these targets. (SPM tries to minimize what is required to use a package.)

I have a PR that addresses improper target filtering. This appears to allow TCA to be used properly. I will close this issue once the PR merges.

**Comment by jpsim** [comment]
Thanks @cgrindel I can build my module that depends on TCA now.

I'm hitting a new error with a different package though. I'll file a new issue for that one.
